[package]
name = "raket"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A simple bash prompt."
repository = "https://github.com/simon-danielsson/raket"
authors = ["Simon Danielsson <contact@simondanielsson.se>"]
keywords = ["bash", "prompt", "terminal", "utility"]
homepage = "https://www.simondanielsson.se"
rust-version = "1.94.0"

[dependencies]
chrono = "0.4.44"
dirs = "6.0.0"
